CREATE DATABASE aplis;

USE aplis;

CREATE TABLE medicos(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    CRM VARCHAR(255) NOT NULL,
    UFCRM VARCHAR(255) NOT NULL
);

CREATE TABLE pacientes(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    DataNascimento DATE NOT NULL,
    Carteirinha VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL
);

